# 调试模式
debug: false

# 限制设置
limits:
  max-peek-distance: 50.0  # 最大观察距离
  block-container-interaction: true  # 是否阻止观察者打开容器
  cooldowns: 60 # 观察冷却时间(秒)

# 隐私设置
privacy:
  request-timeout: 30      # 请求超时时间(秒)
  cooldown:
    enabled: true         # 是否启用请求冷却
    duration: 60        # 冷却时间(秒)
  sounds:
    request: BLOCK_NOTE_BLOCK_PLING    # 请求音效
    accept: ENTITY_PLAYER_LEVELUP      # 接受音效
    deny: BLOCK_ANVIL_LAND            # 拒绝音效

# 声音设置
sounds:
  start-peek: ENTITY_ENDERMAN_TELEPORT  # 开始观察音效
  end-peek: ENTITY_ENDERMAN_TELEPORT    # 结束观察音效

# 统计设置
statistics:
  enabled: true           # 是否启用统计
  save-interval: 600      # 自动保存间隔(秒)

# 文件设置
files:
  stats: "stats.yml"      # 统计文件名
  states: "states.yml"    # 状态文件名

# 语言设置
language: "zh_CN"  # 默认语言