name: Peek
version: '${project.version}'
main: ict.minesunshineone.peek.PeekPlugin
api-version: '1.20'
authors: [MineSunshineOne]
description: A plugin that allows players to peek at other players
website: https://github.com/MineSunshineOne/Peek
folia-supported: true

commands:
  peek:
    description: Main command for Peek plugin
    usage: /peek <player>
    aliases: [p]

permissions:
  peek.use:
    description: Allows using the peek command
    default: op
  peek.bypass:
    description: Bypass privacy mode
    default: op
  peek.nocooldown:
    description: Bypass cooldown
    default: op

softdepend: [PlaceholderAPI] 