name: Peek
version: '1.0'
main: ict.minesunshineone.peek.PeekPlugin
api-version: '1.20'
author: MineSunshineOne
description: 一个允许玩家临时观察其他玩家的插件
folia-supported: true

commands:
  peek:
    description: 观察其他玩家
    usage: |-
      使用 Adventure API 的 MiniMessage 格式:
      <click:run_command:/peek><hover:show_text:'点击查看用法'>/peek</click>
      <gray>/peek <玩家名></gray> - 观察指定玩家
      <gray>/peek exit</gray> - 退出观察模式
      <gray>/peek stats</gray> - 查看个人观察统计
      <gray>/peek privacy</gray> - 切换私人模式
      <gray>/peek accept</gray> - 接受观察请求
      <gray>/peek deny</gray> - 拒绝观察请求
    permission: peek.use
    permission-message: §c你没有权限使用此命令！

permissions:
  peek.use:
    description: 允许使用peek命令
    default: op
  peek.nocooldown:
    description: 允许绕过冷却时间限制
    default: op
  peek.stats:
    description: 允许查看观察统计信息
    default: true 
  peek.privacy:
    description: 允许使用私人模式
    default: true

softdepend: [PlaceholderAPI] 